const tenet = {
  rooms: [
    {
      roomNumber: 101,
      tenetName: "Brandon Williams",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 102,
      tenetName: "Randolph Simmons",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 103,
      tenetName: "Joe Cruz",
      guestName: "undefined",
      roomRate: 290,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 104,
      tenetName: "LardIncel",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 105,
      tenetName: "NO CHANGE",
      guestName: "undefined",
      roomRate: "undefined",
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 106,
      tenetName: "Getechew Kacha",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 107,
      tenetName: "Dontez Micknon",
      guestName: "undefined",
      roomRate: 278,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 108,
      tenetName: "Terry Smith",
      guestName: "undefined",
      roomRate: 290,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 109,
      tenetName: "guest 9",
      guestName: "undefined",
      roomRate: 290,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 110,
      tenetName: "NO CHANGE",
      guestName: "undefined",
      roomRate: 290,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 111,
      tenetName: "Donald Snyder",
      guestName: "undefined",
      roomRate: 290,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 112,
      tenetName: "David Scott",
      guestName: "undefined",
      roomRate: 290,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 114,
      tenetName: "M A",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 115,
      tenetName: "Tywann Morris",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 116,
      tenetName: "Jeff Declout",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 201,
      tenetName: "Juan",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 202,
      tenetName: "Vaccant",
      guestName: "undefined",
      roomRate: "undefined",
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 203,
      tenetName: "Donald Walton",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 204,
      tenetName: "Lennox Phillips",
      guestName: "undefined",
      roomRate: 290,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 205,
      tenetName: "Jerry Jamason",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 206,
      tenetName: "Vaccant",
      guestName: "undefined",
      roomRate: "undefined",
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 207,
      tenetName: "Richard Shalk",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 208,
      tenetName: "Freemen Valasco",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 209,
      tenetName: "guest 9",
      guestName: "undefined",
      roomRate: 290,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 210,
      tenetName: "Zenobia Clark",
      guestName: "undefined",
      roomRate: 278,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 211,
      tenetName: "Vaccant",
      guestName: "undefined",
      roomRate: "undefined",
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 212,
      tenetName: "guest 12",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 214,
      tenetName: "Marlon C",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 215,
      tenetName: "Nicholas Y",
      guestName: "undefined",
      roomRate: 350,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
    {
      roomNumber: 216,
      tenetName: "Vaccant",
      guestName: "undefined",
      roomRate: 95,
      roomService: "none",
      roomStatus: "occupied",
      roomNotes: "none",
    },
  ],
  printRooms: function() {
    this.rooms.forEach(roomUnit => {
      console.log(`Room Number: ${roomUnit.roomNumber}`);
    });
  },
  openRooms: function() {
    this.rooms.forEach(room => {
      if (room.roomStatus != "occupied") {
        console.log(`Room Number: ${room.roomNumber}`);
      }
    });
  }
};

console.log(tenet.printRooms());
