const tenetobject = {
  rooms: [
    {
      roomNumber: 101,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Brandon Williams",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 102,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Randolph Simmons",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 103,
      roomStatus: "occupied",
      roomRate: 290,
      tenetName: "Joe Cruz",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 104,
      roomStatus: null,
      roomRate: 350,
      tenetName: "LardIncel",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 105,
      roomStatus: null,
      roomRate: null,
      tenetName: "NO CHANGE",
      guestName: null,
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 106,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Getechew Kacha",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 107,
      roomStatus: "occupied",
      roomRate: 278,
      tenetName: "Dontez Micknon",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 108,
      roomStatus: "occupied",
      roomRate: 290,
      tenetName: "Terry Smith",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 109,
      roomStatus: "occupied",
      roomRate: 290,
      tenetName: "guest 9",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 110,
      roomStatus: "vacant",
      roomRate: 290,
      tenetName: "",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 111,
      roomStatus: "occupied",
      roomRate: 290,
      tenetName: "Donald Snyder",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 112,
      roomStatus: "occupied",
      roomRate: 290,
      tenetName: "David Scott",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 114,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "M A",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 115,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Tywann Morris",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 116,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Jeff Declout",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 201,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Juan",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 202,
      roomStatus: "occupied",
      roomRate: "undefined",
      tenetName: "Vaccant",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 203,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Donald Walton",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 204,
      roomStatus: "occupied",
      roomRate: 290,
      tenetName: "Lennox Phillips",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 205,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Jerry Jamason",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 206,
      roomStatus: "occupied",
      roomRate: "undefined",
      tenetName: "Vaccant",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 207,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Richard Shalk",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 208,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Freemen Valasco",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 209,
      roomStatus: "occupied",
      roomRate: 290,
      tenetName: "guest 9",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 210,
      roomStatus: "occupied",
      roomRate: 278,
      tenetName: "Zenobia Clark",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 211,
      roomStatus: "occupied",
      roomRate: "undefined",
      tenetName: "Vaccant",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 212,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "guest 12",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 214,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Marlon C",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 215,
      roomStatus: "occupied",
      roomRate: 350,
      tenetName: "Nicholas Y",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 216,
      roomStatus: "occupied",
      roomRate: 95,
      tenetName: "Vaccant",
      guestName: "undefined",
      roomService: "none",
      roomNotes: "none",
    },
  ],
  // function with intenet object that allows user to set the values of the room
  setRoom: (
    roomNumber,
    tenetName,
    guestName,
    roomRate,
    roomService,
    roomStatus,
    roomNotes
  ) => {
    this.rooms.push({
      roomNumber: roomNumber,
      roomStatus: roomStatus,
      roomRate: roomRate,
      tenetName: tenetName,
      guestName: guestName,
      roomService: roomService,
      roomNotes: roomNotes,
    });
    //we would like to check if the room is occupied to prevent double booking
  },
  printRooms: () => {
    this.rooms.forEach((roomUnit) => {
      console.log(`Room Number: ${roomUnit.roomNumber}`);
      if (roomUnit.roomStatus !== "occupied") {
      }
    });
  },
  openRooms: () => {
    
  },
};

console.log(tenetobject.printRooms());
// console.log(tenetobject.openRooms());
