
const tenetObject = {
  primeRooms: {
    101: {
      roomNumber: 101,
      roomStatus: "occupied",
      tenetName: "Brat Willus",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    102: {
      roomNumber: 102,
      roomStatus: "occupied",
      tenetName: "Rain Sacaro",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    103: {
      roomNumber: 103,
      roomStatus: "occupied",
      tenetName: "Joe Steve",
      roomRate: 290.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    104: {
      roomNumber: 104,
      roomStatus: "dirty",
      tenetName: "Lard Incel",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    105: {
      roomNumber: 105,
      roomStatus: "No Change",
      tenetName: null,
      roomRate: null,
      roomBalance: null,
      balanceDueDate: null,
      guestName: null,
      tenetDocuments: null,
      roomService: null,
      roomNotes: "storage",
    },
    106: {
      roomNumber: 106,
      roomStatus: "occupied",
      tenetName: "Garry Kerry",
      roomRate: 350.00,
      roomBalance: 410.00,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    107: {
      roomNumber: 107,
      roomStatus: "occupied",
      tenetName: "Donny Yen",
      roomRate: 278.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    108: {
      roomNumber: 108,
      roomStatus: "occupied",
      tenetName: "Tim Smith",
      roomRate: 290.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    109: {
      roomNumber: 109,
      roomStatus: "occupied",
      tenetName: "Lawrence Stroll",
      roomRate: 290.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    110: {
      roomNumber: 110,
      roomStatus: "vacant",
      tenetName: "Raiz Common",
      roomRate: 290.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    111: {
      roomNumber: 111,
      roomStatus: "occupied",
      tenetName: "Don Sim",
      roomRate: 290.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    112: {
      roomNumber: 112,
      roomStatus: "occupied",
      tenetName: "Dave Attenborough",
      roomRate: 290.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    113: {},
    114: {
      roomNumber: 114,
      roomStatus: "occupied",
      tenetName: "M A",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    115: {
      roomNumber: 115,
      roomStatus: "occupied",
      tenetName: "Taylor McKenzie",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    116: {
      roomNumber: 116,
      roomStatus: "occupied",
      tenetName: "Jeff Doug",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    201: {
      roomNumber: 201,
      roomStatus: "occupied",
      tenetName: "Juan",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    202: {
      roomNumber: 202,
      roomStatus: "occupied",
      tenetName: "Vaccant",
      roomRate: "un.00defined",
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    203: {
      roomNumber: 203,
      roomStatus: "occupied",
      tenetName: "Dairy Winny",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    204: {
      roomNumber: 204,
      roomStatus: "occupied",
      tenetName: "Len Phil",
      roomRate: 290.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    205: {
      roomNumber: 205,
      roomStatus: "occupied",
      tenetName: "Jerry Jackson",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    206: {
      roomNumber: 206,
      roomStatus: "occupied",
      tenetName: "Vaccant",
      roomRate: "undefined",
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    207: {
      roomNumber: 207,
      roomStatus: "occupied",
      tenetName: "Rich Brain",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    208: {
      roomNumber: 208,
      roomStatus: "occupied",
      tenetName: "Flamingo Vector",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    209: {
      roomNumber: 209,
      roomStatus: "occupied",
      tenetName: "guest 9",
      roomRate: 290.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    210: {
      roomNumber: 210,
      roomStatus: "occupied",
      tenetName: "Zenobia Clark",
      roomRate: 278.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    211: {
      roomNumber: 211,
      roomStatus: "occupied",
      tenetName: "Vaccant",
      roomRate: "undefined",
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    212: {
      roomNumber: 212,
      roomStatus: "occupied",
      tenetName: "guest 12",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    214: {
      roomNumber: 214,
      roomStatus: "occupied",
      tenetName: "Marry C",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    215: {
      roomNumber: 215,
      roomStatus: "occupied",
      tenetName: "Nick Y",
      roomRate: 350.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
    216: {
      roomNumber: 216,
      roomStatus: "vaccant",
      tenetName: "Yuki Tsuno",
      roomRate: 95.00,
      roomBalance: 0.0,
      balanceDueDate: '1.2.24',
      guestName: "undefined",
      tenetDocuments: 'file.pdf',
      roomService: "none",
      roomNotes: "none",
    },
  }
};

