// array of objects for each room mock v2
const tenetObject = {
  _unitRooms: [
    {
      roomNumber: 101,
      roomStatus: false,
      tenetName: "Brat Willus",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 350,
      roomBalance: 0,
      balanceDueDate: "April 6, 2025",
      checkOutDate: "April 5, 2025",
      smokingRoom: false,
      carTag: "XYZ123",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 102,
      roomStatus: false,
      tenetName: "Rain Sacaro",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 350,
      roomBalance: 0,
      balanceDueDate: "April 7, 2025",
      checkOutDate: "April 6, 2025",
      smokingRoom: false,
      carTag: "XYZ124",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 103,
      roomStatus: false,
      tenetName: "Joe Steve",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 8, 2025",
      checkOutDate: "April 7, 2025",
      smokingRoom: false,
      carTag: "XYZ125",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 104,
      roomStatus: false,
      tenetName: "Lard Incel",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 350,
      roomBalance: 0,
      balanceDueDate: "April 9, 2025",
      checkOutDate: "April 8, 2025",
      smokingRoom: false,
      carTag: "XYZ126",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 105,
      roomStatus: null,
      tenetName: null,
      accomodationPeriodDaily: null,
      accomadationPeriodWeekly: null,
      roomRate: null,
      roomBalance: null,
      balanceDueDate: null,
      checkOutDate: null,
      smokingRoom: false,
      carTag: null,
      guestName: null,
      tenetDocuments: null,
      roomService: null,
      roomNotes: "storage",
    },
    {
      roomNumber: 106,
      roomStatus: false,
      tenetName: "Garry Kerry",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 350,
      roomBalance: 410,
      balanceDueDate: "April 10, 2025",
      checkOutDate: "April 9, 2025",
      smokingRoom: false,
      carTag: "XYZ127",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 107,
      roomStatus: false,
      tenetName: "Donny Yen",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 278,
      roomBalance: 0,
      balanceDueDate: "April 11, 2025",
      checkOutDate: "April 10, 2025",
      smokingRoom: false,
      carTag: "XYZ128",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 108,
      roomStatus: false,
      tenetName: "Tim Smith",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 12, 2025",
      checkOutDate: "April 11, 2025",
      smokingRoom: false,
      carTag: "XYZ129",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 109,
      roomStatus: false,
      tenetName: "Lawrence Stroll",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 13, 2025",
      checkOutDate: "April 12, 2025",
      smokingRoom: false,
      carTag: "XYZ130",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 110,
      roomStatus: true,
      tenetName: "Raiz Common",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 14, 2025",
      checkOutDate: "April 13, 2025",
      smokingRoom: false,
      carTag: "XYZ131",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 111,
      roomStatus: false,
      tenetName: "Don Sim",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 15, 2025",
      checkOutDate: "April 14, 2025",
      smokingRoom: false,
      carTag: "XYZ132",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 112,
      roomStatus: false,
      tenetName: "Dave Attenborough",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 16, 2025",
      checkOutDate: "April 15, 2025",
      smokingRoom: false,
      carTag: "XYZ133",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 114,
      roomStatus: false,
      tenetName: "Liam Stone",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 17, 2025",
      checkOutDate: "April 16, 2025",
      smokingRoom: false,
      carTag: "XYZ134",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 115,
      roomStatus: false,
      tenetName: "Nina Dobrev",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 18, 2025",
      checkOutDate: "April 17, 2025",
      smokingRoom: false,
      carTag: "XYZ135",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 116,
      roomStatus: true,
      tenetName: "Emma Frost",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 19, 2025",
      checkOutDate: "April 18, 2025",
      smokingRoom: false,
      carTag: "XYZ136",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 201,
      roomStatus: true,
      tenetName: "Sam Worthington",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 350,
      roomBalance: 0,
      balanceDueDate: "April 20, 2025",
      checkOutDate: "April 19, 2025",
      smokingRoom: false,
      carTag: "XYZ137",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 202,
      roomStatus: false,
      tenetName: "Tony Stark",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 350,
      roomBalance: 200,
      balanceDueDate: "April 21, 2025",
      checkOutDate: "April 20, 2025",
      smokingRoom: false,
      carTag: "XYZ138",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 203,
      roomStatus: false,
      tenetName: "Bruce Wayne",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 350,
      roomBalance: 400,
      balanceDueDate: "April 22, 2025",
      checkOutDate: "April 21, 2025",
      smokingRoom: false,
      carTag: "XYZ139",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 204,
      roomStatus: true,
      tenetName: "Clark Kent",
      accomodationPeriodDaily: true,
      accomadationPeriodWeekly: false,
      roomRate: 350,
      roomBalance: 0,
      balanceDueDate: "April 23, 2025",
      checkOutDate: "April 22, 2025",
      smokingRoom: false,
      carTag: "XYZ140",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 205,
      roomStatus: false,
      tenetName: "Barry Allen",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 24, 2025",
      checkOutDate: "April 23, 2025",
      smokingRoom: false,
      carTag: "XYZ141",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 206,
      roomStatus: true,
      tenetName: "Wanda Maximoff",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 25, 2025",
      checkOutDate: "April 24, 2025",
      smokingRoom: false,
      carTag: "XYZ142",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 207,
      roomStatus: false,
      tenetName: "Vision",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 26, 2025",
      checkOutDate: "April 25, 2025",
      smokingRoom: false,
      carTag: "XYZ143",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 208,
      roomStatus: true,
      tenetName: "Steve Rogers",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 27, 2025",
      checkOutDate: "April 26, 2025",
      smokingRoom: false,
      carTag: "XYZ144",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 209,
      roomStatus: true,
      tenetName: "Natasha Romanoff",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 28, 2025",
      checkOutDate: "April 27, 2025",
      smokingRoom: false,
      carTag: "XYZ145",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 210,
      roomStatus: false,
      tenetName: "Peter Parker",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 29, 2025",
      checkOutDate: "April 28, 2025",
      smokingRoom: false,
      carTag: "XYZ146",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 211,
      roomStatus: false,
      tenetName: "Stephen Strange",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "April 30, 2025",
      checkOutDate: "April 29, 2025",
      smokingRoom: false,
      carTag: "XYZ147",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 212,
      roomStatus: false,
      tenetName: "Nick Fury",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "May 1, 2025",
      checkOutDate: "April 30, 2025",
      smokingRoom: false,
      carTag: "XYZ148",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 214,
      roomStatus: false,
      tenetName: "Carol Danvers",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "May 3, 2025",
      checkOutDate: "May 2, 2025",
      smokingRoom: false,
      carTag: "XYZ150",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 215,
      roomStatus: false,
      tenetName: "Scott Lang",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "May 4, 2025",
      checkOutDate: "May 3, 2025",
      smokingRoom: false,
      carTag: "XYZ151",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
    {
      roomNumber: 216,
      roomStatus: false,
      tenetName: "Hope van Dyne",
      accomodationPeriodDaily: false,
      accomadationPeriodWeekly: true,
      roomRate: 290,
      roomBalance: 0,
      balanceDueDate: "May 5, 2025",
      checkOutDate: "May 4, 2025",
      smokingRoom: false,
      carTag: "XYZ152",
      guestName: "None",
      tenetDocuments: "file.pdf",
      roomService: "none",
      roomNotes: "none",
    },
  ],

  // read private methods
  get roomNums() {
    return this._unitRooms;
  },

  //   write private methods

  vacantRooms() {
    //1. prints out the vacant rooms by accessing refrence to the tenetObject
    //2. read values and keys of guest tenetObject that have been put into a array of vacant rooms and non vacant rooms,
    // reads/prints room number, roomStatus
    // returns room numbers
    // perhaphs refractor to use simple truthy/falsy values instead of strings like vacant or occupid, refractoring DB will be necessary, not using binary values could allow chekcs for room status: like broken, or on change... etc
    console.log();
    console.log("Vergil $:Printing out all vacant rooms\n");
    for (let unitRooms in tenetObject._unitRooms) {
      if (tenetObject._unitRooms[unitRooms].roomStatus == true) {
        // add to vacant room # to vacant rooms array
        console.log(
          tenetObject._unitRooms[unitRooms].roomNumber,
          tenetObject._unitRooms[unitRooms].roomStatus
        );
      }
    }
  },

  listRooms() {
    // here the for loop variable will itterate the 'unitRooms' for value in DB: key is 1st degree child in _unitRooms value
    console.log();
    console.log("Vergil $:Printing out all rooms. . .");
    for (let unitRooms in tenetObject._unitRooms) {
      console.log(
        "Room #" +
          tenetObject._unitRooms[unitRooms].roomNumber +
          " : " +
          tenetObject._unitRooms[unitRooms].tenetName
      );
    }
  },

  dailyReport() {
    let currentDate = new Date();
    //inlcudes what day is the present, present day transaction (cash,credit)
    console.log("\nVergil $: Today is... ");
    console.log("Vergil $: " + currentDate);
    // transactions();
    tenetObject.listRooms();
  },

  // program Read functions
};

// current debugging
tenetObject.vacantRooms();


// future Debugging
// console.log(tenetObject.roomNums);
// tenetObject.dailyReport();
